// Code generated by protocolgen; DO NOT EDIT.
// Source: ../../../protocol/warren.schema.json

// Package protocol holds the constants from protocol/warren.schema.json.
// The schema is authoritative; this file is regenerated by `go generate`.
package protocol

const LogicalVersion = "2.0"

// Binary DENB envelope.
const (
	BinaryWireVersion uint8 = 1
)

var BinaryMagic = []byte{0x44, 0x45, 0x4E, 0x42}

const (
	DirectionClientToHost uint8 = 1
	DirectionHostToClient uint8 = 2
)

const (
	KindInput       uint8 = 1
	KindOutput      uint8 = 2
	KindAtomicState uint8 = 3
)

const (
	MaxHeader             = 16384
	MaxPayload            = 8388608
	MaxAtomicStatePayload = 67108864
)

// BinaryPrefixLength is magic(4) + version(1) + direction(1) + kind(1) + headerLength(4) + payloadLength(4).
const BinaryPrefixLength = 15

// Field offsets inside the DENB prefix. u32 fields are big-endian.
const (
	MagicOffset         = 0
	VersionOffset       = 4
	DirectionOffset     = 5
	KindOffset          = 6
	HeaderLengthOffset  = 7
	PayloadLengthOffset = 11
	HeaderStartOffset   = 15
)

// Negotiated capability identifiers. Order is the canonical order returned by the Host.
var Capabilities = []string{
	"roster-delta",
	"agent-timeline-v1",
	"agent-interactions-v1",
	"agent-interrupt-v1",
	"agent-attachments-v1",
}

// TerminalStateFormats is the set of opaque terminal-state formats a client can install atomically.
var TerminalStateFormats = []string{
	"ghostline-vt-replay-v1",
}
