// Command protocolgen reads protocol/warren.schema.json and writes a Go
// file with the constants. Run via `go generate ./Headless/internal/protocol`
// or directly. The schema is the single source of truth; do not edit the
// generated file by hand.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type schema struct {
	Properties struct {
		LogicalVersion struct {
			Const string `json:"const"`
		} `json:"logicalVersion"`
		BinaryEnvelope struct {
			Properties struct {
				Magic struct {
					Const []int `json:"const"`
				} `json:"magic"`
				WireVersion struct {
					Const int `json:"const"`
				} `json:"wireVersion"`
				Directions struct {
					Properties struct {
						ClientToHost struct {
							Const int `json:"const"`
						} `json:"clientToHost"`
						HostToClient struct {
							Const int `json:"const"`
						} `json:"hostToClient"`
					} `json:"properties"`
				} `json:"directions"`
				Kinds struct {
					Properties struct {
						Input struct {
							Const int `json:"const"`
						} `json:"input"`
						Output struct {
							Const int `json:"const"`
						} `json:"output"`
						AtomicState struct {
							Const int `json:"const"`
						} `json:"atomicState"`
					} `json:"properties"`
				} `json:"kinds"`
				Limits struct {
					Properties struct {
						MaxHeader struct {
							Const int `json:"const"`
						} `json:"maxHeader"`
						MaxPayload struct {
							Const int `json:"const"`
						} `json:"maxPayload"`
						MaxAtomicStatePayload struct {
							Const int `json:"const"`
						} `json:"maxAtomicStatePayload"`
					} `json:"properties"`
				} `json:"limits"`
				Layout struct {
					Properties struct {
						PrefixLength struct {
							Const int `json:"const"`
						} `json:"prefixLength"`
					} `json:"properties"`
				} `json:"layout"`
			} `json:"properties"`
		} `json:"binaryEnvelope"`
		Capabilities struct {
			Items struct {
				Enum []string `json:"enum"`
			} `json:"items"`
		} `json:"capabilities"`
		TerminalStateFormats struct {
			Items struct {
				Enum []string `json:"enum"`
			} `json:"items"`
		} `json:"terminalStateFormats"`
	} `json:"properties"`
}

func main() {
	schemaPath := flag.String("schema", "protocol/warren.schema.json", "path to warren.schema.json")
	outPath := flag.String("out", "Headless/internal/protocol/wire.go", "output Go file")
	flag.Parse()

	data, err := os.ReadFile(*schemaPath)
	if err != nil {
		die("read schema: %v", err)
	}
	var s schema
	if err := json.Unmarshal(data, &s); err != nil {
		die("parse schema: %v", err)
	}

	be := s.Properties.BinaryEnvelope.Properties
	if len(be.Magic.Const) != 4 {
		die("binaryEnvelope.magic must have 4 bytes, got %d", len(be.Magic.Const))
	}
	if s.Properties.LogicalVersion.Const == "" {
		die("logicalVersion const is empty")
	}
	if len(s.Properties.Capabilities.Items.Enum) == 0 {
		die("capabilities enum is empty")
	}
	if len(s.Properties.TerminalStateFormats.Items.Enum) == 0 {
		die("terminalStateFormats enum is empty")
	}

	magicBytes := byteSlice(be.Magic.Const)
	caps := s.Properties.Capabilities.Items.Enum
	formats := s.Properties.TerminalStateFormats.Items.Enum

	body := new(strings.Builder)
	fmt.Fprintf(body, "// Code generated by protocolgen; DO NOT EDIT.\n")
	fmt.Fprintf(body, "// Source: %s\n", filepath.ToSlash(*schemaPath))
	fmt.Fprintf(body, "\n")
	fmt.Fprintf(body, "// Package protocol holds the constants from protocol/warren.schema.json.\n")
	fmt.Fprintf(body, "// The schema is authoritative; this file is regenerated by `go generate`.\n")
	fmt.Fprintf(body, "package protocol\n")
	fmt.Fprintf(body, "\n")
	fmt.Fprintf(body, "const LogicalVersion = %q\n", s.Properties.LogicalVersion.Const)
	fmt.Fprintf(body, "\n")
	fmt.Fprintf(body, "// Binary DENB envelope.\n")
	fmt.Fprintf(body, "const (\n")
	fmt.Fprintf(body, "\tBinaryWireVersion uint8 = %d\n", be.WireVersion.Const)
	fmt.Fprintf(body, ")\n")
	fmt.Fprintf(body, "\n")
	fmt.Fprintf(body, "var BinaryMagic = []byte{%s}\n", magicBytes)
	fmt.Fprintf(body, "\n")
	fmt.Fprintf(body, "const (\n")
	fmt.Fprintf(body, "\tDirectionClientToHost uint8 = %d\n", be.Directions.Properties.ClientToHost.Const)
	fmt.Fprintf(body, "\tDirectionHostToClient uint8 = %d\n", be.Directions.Properties.HostToClient.Const)
	fmt.Fprintf(body, ")\n")
	fmt.Fprintf(body, "\n")
	fmt.Fprintf(body, "const (\n")
	fmt.Fprintf(body, "\tKindInput       uint8 = %d\n", be.Kinds.Properties.Input.Const)
	fmt.Fprintf(body, "\tKindOutput      uint8 = %d\n", be.Kinds.Properties.Output.Const)
	fmt.Fprintf(body, "\tKindAtomicState uint8 = %d\n", be.Kinds.Properties.AtomicState.Const)
	fmt.Fprintf(body, ")\n")
	fmt.Fprintf(body, "\n")
	fmt.Fprintf(body, "const (\n")
	fmt.Fprintf(body, "\tMaxHeader             = %d\n", be.Limits.Properties.MaxHeader.Const)
	fmt.Fprintf(body, "\tMaxPayload            = %d\n", be.Limits.Properties.MaxPayload.Const)
	fmt.Fprintf(body, "\tMaxAtomicStatePayload = %d\n", be.Limits.Properties.MaxAtomicStatePayload.Const)
	fmt.Fprintf(body, ")\n")
	fmt.Fprintf(body, "\n")
	fmt.Fprintf(body, "// BinaryPrefixLength is magic(4) + version(1) + direction(1) + kind(1) + headerLength(4) + payloadLength(4).\n")
	fmt.Fprintf(body, "const BinaryPrefixLength = %d\n", be.Layout.Properties.PrefixLength.Const)
	fmt.Fprintf(body, "\n")
	fmt.Fprintf(body, "// Field offsets inside the DENB prefix. u32 fields are big-endian.\n")
	fmt.Fprintf(body, "const (\n")
	fmt.Fprintf(body, "\tMagicOffset         = 0\n")
	fmt.Fprintf(body, "\tVersionOffset       = 4\n")
	fmt.Fprintf(body, "\tDirectionOffset     = 5\n")
	fmt.Fprintf(body, "\tKindOffset          = 6\n")
	fmt.Fprintf(body, "\tHeaderLengthOffset  = 7\n")
	fmt.Fprintf(body, "\tPayloadLengthOffset = 11\n")
	fmt.Fprintf(body, "\tHeaderStartOffset   = %d\n", be.Layout.Properties.PrefixLength.Const)
	fmt.Fprintf(body, ")\n")
	fmt.Fprintf(body, "\n")
	fmt.Fprintf(body, "// Negotiated capability identifiers. Order is the canonical order returned by the Host.\n")
	fmt.Fprintf(body, "var Capabilities = []string{\n")
	for _, c := range caps {
		fmt.Fprintf(body, "\t%q,\n", c)
	}
	fmt.Fprintf(body, "}\n")
	fmt.Fprintf(body, "\n")
	fmt.Fprintf(body, "// TerminalStateFormats is the set of opaque terminal-state formats a client can install atomically.\n")
	fmt.Fprintf(body, "var TerminalStateFormats = []string{\n")
	for _, f := range formats {
		fmt.Fprintf(body, "\t%q,\n", f)
	}
	fmt.Fprintf(body, "}\n")

	if err := os.MkdirAll(filepath.Dir(*outPath), 0o755); err != nil {
		die("mkdir: %v", err)
	}
	if err := os.WriteFile(*outPath, []byte(body.String()), 0o644); err != nil {
		die("write: %v", err)
	}
	fmt.Fprintf(os.Stderr, "wrote %s from %s\n", *outPath, *schemaPath)
}

func byteSlice(values []int) string {
	parts := make([]string, len(values))
	for i, v := range values {
		if v < 0 || v > 255 {
			die("magic byte %d out of range", v)
		}
		parts[i] = fmt.Sprintf("0x%02X", v)
	}
	return strings.Join(parts, ", ")
}

func die(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "protocolgen: "+format+"\n", args...)
	os.Exit(1)
}
